name: Publish
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: |
        python3 -m pip install --upgrade pip
        pip3 install build
        python3 -m build
    - uses: actions/upload-artifact@v4
      with:
        path: dist/

  publish:
    needs: ['build']
    environment: 'publish'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages_dir: artifact/
